//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4963.
// 
namespace EDL.EDLWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EDLWSSoap", Namespace="http://tempuri.org/")]
    public partial class EDLWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public EDLWS() {
            this.Url = "http://172.17.41.64/edl_web/WS/EDLWS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificaConexao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerificaConexao() {
            object[] results = this.Invoke("VerificaConexao", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginVerificaConexao(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VerificaConexao", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndVerificaConexao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaVersaoEDLColetor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetornaVersaoEDLColetor() {
            object[] results = this.Invoke("RetornaVersaoEDLColetor", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaVersaoEDLColetor(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaVersaoEDLColetor", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRetornaVersaoEDLColetor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaVersaoEDLAtualizaVersao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetornaVersaoEDLAtualizaVersao() {
            object[] results = this.Invoke("RetornaVersaoEDLAtualizaVersao", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaVersaoEDLAtualizaVersao(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaVersaoEDLAtualizaVersao", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRetornaVersaoEDLAtualizaVersao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviaAtualizadorNovo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VersaoEDL EnviaAtualizadorNovo() {
            object[] results = this.Invoke("EnviaAtualizadorNovo", new object[0]);
            return ((VersaoEDL)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEnviaAtualizadorNovo(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EnviaAtualizadorNovo", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public VersaoEDL EndEnviaAtualizadorNovo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((VersaoEDL)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogRecusaSemNFe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LogRecusaSemNFe(int tipoRecebimento, int filial, int fornecedor, int notaFiscal, string serie, string motivo, string login) {
            object[] results = this.Invoke("LogRecusaSemNFe", new object[] {
                        tipoRecebimento,
                        filial,
                        fornecedor,
                        notaFiscal,
                        serie,
                        motivo,
                        login});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogRecusaSemNFe(int tipoRecebimento, int filial, int fornecedor, int notaFiscal, string serie, string motivo, string login, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LogRecusaSemNFe", new object[] {
                        tipoRecebimento,
                        filial,
                        fornecedor,
                        notaFiscal,
                        serie,
                        motivo,
                        login}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLogRecusaSemNFe(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogRecusaNFe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LogRecusaNFe(int tipoRecebimento, int filial, string chaveAcesso, string motivo, string login) {
            object[] results = this.Invoke("LogRecusaNFe", new object[] {
                        tipoRecebimento,
                        filial,
                        chaveAcesso,
                        motivo,
                        login});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogRecusaNFe(int tipoRecebimento, int filial, string chaveAcesso, string motivo, string login, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LogRecusaNFe", new object[] {
                        tipoRecebimento,
                        filial,
                        chaveAcesso,
                        motivo,
                        login}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLogRecusaNFe(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistraRomaneioPedido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistraRomaneioPedido(FornecedorNotaManual nota, PedidoItens[] itens, int matricula, string login) {
            object[] results = this.Invoke("RegistraRomaneioPedido", new object[] {
                        nota,
                        itens,
                        matricula,
                        login});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegistraRomaneioPedido(FornecedorNotaManual nota, PedidoItens[] itens, int matricula, string login, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegistraRomaneioPedido", new object[] {
                        nota,
                        itens,
                        matricula,
                        login}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRegistraRomaneioPedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistraRomaneio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistraRomaneio(NotaFiscalManual nota, int matricula, string login) {
            object[] results = this.Invoke("RegistraRomaneio", new object[] {
                        nota,
                        matricula,
                        login});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegistraRomaneio(NotaFiscalManual nota, int matricula, string login, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegistraRomaneio", new object[] {
                        nota,
                        matricula,
                        login}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRegistraRomaneio(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarDevolucao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistrarDevolucao(Devolucao devolucao, DevolucaoItem[] devolucaoItem, string login) {
            object[] results = this.Invoke("RegistrarDevolucao", new object[] {
                        devolucao,
                        devolucaoItem,
                        login});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegistrarDevolucao(Devolucao devolucao, DevolucaoItem[] devolucaoItem, string login, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegistrarDevolucao", new object[] {
                        devolucao,
                        devolucaoItem,
                        login}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRegistrarDevolucao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaProdutoDevolucao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DevolucaoItem RetornaProdutoDevolucao(string codigoBarra, int filial, int idDevolucao) {
            object[] results = this.Invoke("RetornaProdutoDevolucao", new object[] {
                        codigoBarra,
                        filial,
                        idDevolucao});
            return ((DevolucaoItem)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaProdutoDevolucao(string codigoBarra, int filial, int idDevolucao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaProdutoDevolucao", new object[] {
                        codigoBarra,
                        filial,
                        idDevolucao}, callback, asyncState);
        }
        
        /// <remarks/>
        public DevolucaoItem EndRetornaProdutoDevolucao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DevolucaoItem)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornarDevolucao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Devolucao[] RetornarDevolucao(int filial) {
            object[] results = this.Invoke("RetornarDevolucao", new object[] {
                        filial});
            return ((Devolucao[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornarDevolucao(int filial, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornarDevolucao", new object[] {
                        filial}, callback, asyncState);
        }
        
        /// <remarks/>
        public Devolucao[] EndRetornarDevolucao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Devolucao[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistraNFManualPedidoDataJuliana", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistraNFManualPedidoDataJuliana(FornecedorNotaManual nota, PedidoItens[] itens, int matricula, int dataJuliana, int sequencialJuliana) {
            object[] results = this.Invoke("RegistraNFManualPedidoDataJuliana", new object[] {
                        nota,
                        itens,
                        matricula,
                        dataJuliana,
                        sequencialJuliana});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegistraNFManualPedidoDataJuliana(FornecedorNotaManual nota, PedidoItens[] itens, int matricula, int dataJuliana, int sequencialJuliana, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegistraNFManualPedidoDataJuliana", new object[] {
                        nota,
                        itens,
                        matricula,
                        dataJuliana,
                        sequencialJuliana}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRegistraNFManualPedidoDataJuliana(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistraNFManualPedido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistraNFManualPedido(FornecedorNotaManual nota, PedidoItens[] itens, int matricula) {
            object[] results = this.Invoke("RegistraNFManualPedido", new object[] {
                        nota,
                        itens,
                        matricula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegistraNFManualPedido(FornecedorNotaManual nota, PedidoItens[] itens, int matricula, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegistraNFManualPedido", new object[] {
                        nota,
                        itens,
                        matricula}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRegistraNFManualPedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaPedidoItens", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pedido RetornaPedidoItens(int dataJuliana, int sequencia, int filial) {
            object[] results = this.Invoke("RetornaPedidoItens", new object[] {
                        dataJuliana,
                        sequencia,
                        filial});
            return ((Pedido)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaPedidoItens(int dataJuliana, int sequencia, int filial, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaPedidoItens", new object[] {
                        dataJuliana,
                        sequencia,
                        filial}, callback, asyncState);
        }
        
        /// <remarks/>
        public Pedido EndRetornaPedidoItens(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Pedido)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistraNFManual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistraNFManual(NotaFiscalManual nota, int matricula) {
            object[] results = this.Invoke("RegistraNFManual", new object[] {
                        nota,
                        matricula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegistraNFManual(NotaFiscalManual nota, int matricula, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegistraNFManual", new object[] {
                        nota,
                        matricula}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRegistraNFManual(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaProdutoRomaneio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NegociacaoProduto RetornaProdutoRomaneio(string codigoBarra, int fornecedor, int filial) {
            object[] results = this.Invoke("RetornaProdutoRomaneio", new object[] {
                        codigoBarra,
                        fornecedor,
                        filial});
            return ((NegociacaoProduto)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaProdutoRomaneio(string codigoBarra, int fornecedor, int filial, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaProdutoRomaneio", new object[] {
                        codigoBarra,
                        fornecedor,
                        filial}, callback, asyncState);
        }
        
        /// <remarks/>
        public NegociacaoProduto EndRetornaProdutoRomaneio(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((NegociacaoProduto)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NegociacaoProduto RetornaProduto(string codigoBarra, int fornecedor, int filial) {
            object[] results = this.Invoke("RetornaProduto", new object[] {
                        codigoBarra,
                        fornecedor,
                        filial});
            return ((NegociacaoProduto)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaProduto(string codigoBarra, int fornecedor, int filial, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaProduto", new object[] {
                        codigoBarra,
                        fornecedor,
                        filial}, callback, asyncState);
        }
        
        /// <remarks/>
        public NegociacaoProduto EndRetornaProduto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((NegociacaoProduto)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaFornecedorJuridico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RetornaFornecedorJuridico(string cnpj) {
            object[] results = this.Invoke("RetornaFornecedorJuridico", new object[] {
                        cnpj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaFornecedorJuridico(string cnpj, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaFornecedorJuridico", new object[] {
                        cnpj}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndRetornaFornecedorJuridico(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaFornecedorJuridicoControladora", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FornecedorJuridico[] RetornaFornecedorJuridicoControladora(int fornecedor) {
            object[] results = this.Invoke("RetornaFornecedorJuridicoControladora", new object[] {
                        fornecedor});
            return ((FornecedorJuridico[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaFornecedorJuridicoControladora(int fornecedor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaFornecedorJuridicoControladora", new object[] {
                        fornecedor}, callback, asyncState);
        }
        
        /// <remarks/>
        public FornecedorJuridico[] EndRetornaFornecedorJuridicoControladora(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FornecedorJuridico[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaFornecedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FornecedorNotaManual RetornaFornecedor(int fornecedorGestao, int fornecedorFilial) {
            object[] results = this.Invoke("RetornaFornecedor", new object[] {
                        fornecedorGestao,
                        fornecedorFilial});
            return ((FornecedorNotaManual)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaFornecedor(int fornecedorGestao, int fornecedorFilial, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaFornecedor", new object[] {
                        fornecedorGestao,
                        fornecedorFilial}, callback, asyncState);
        }
        
        /// <remarks/>
        public FornecedorNotaManual EndRetornaFornecedor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FornecedorNotaManual)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistraNFe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistraNFe(Nfe nfe, int matricula) {
            object[] results = this.Invoke("RegistraNFe", new object[] {
                        nfe,
                        matricula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegistraNFe(Nfe nfe, int matricula, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegistraNFe", new object[] {
                        nfe,
                        matricula}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRegistraNFe(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaFluxoSAP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetornaFluxoSAP(string Key) {
            object[] results = this.Invoke("RetornaFluxoSAP", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaFluxoSAP(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaFluxoSAP", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRetornaFluxoSAP(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaNFe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Nfe RetornaNFe(string chaveAcesso) {
            object[] results = this.Invoke("RetornaNFe", new object[] {
                        chaveAcesso});
            return ((Nfe)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaNFe(string chaveAcesso, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaNFe", new object[] {
                        chaveAcesso}, callback, asyncState);
        }
        
        /// <remarks/>
        public Nfe EndRetornaNFe(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Nfe)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutenticarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario AutenticarUsuario(int matricula, string senha) {
            object[] results = this.Invoke("AutenticarUsuario", new object[] {
                        matricula,
                        senha});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAutenticarUsuario(int matricula, string senha, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AutenticarUsuario", new object[] {
                        matricula,
                        senha}, callback, asyncState);
        }
        
        /// <remarks/>
        public Usuario EndAutenticarUsuario(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutenticarUsuarioComIp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario AutenticarUsuarioComIp(int matricula, string senha, string ipColetor) {
            object[] results = this.Invoke("AutenticarUsuarioComIp", new object[] {
                        matricula,
                        senha,
                        ipColetor});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAutenticarUsuarioComIp(int matricula, string senha, string ipColetor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AutenticarUsuarioComIp", new object[] {
                        matricula,
                        senha,
                        ipColetor}, callback, asyncState);
        }
        
        /// <remarks/>
        public Usuario EndAutenticarUsuarioComIp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RealizarDownloadNFePorLoja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DownloadXMlNFe RealizarDownloadNFePorLoja(string chaveAcessoNFe, int filial) {
            object[] results = this.Invoke("RealizarDownloadNFePorLoja", new object[] {
                        chaveAcessoNFe,
                        filial});
            return ((DownloadXMlNFe)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRealizarDownloadNFePorLoja(string chaveAcessoNFe, int filial, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RealizarDownloadNFePorLoja", new object[] {
                        chaveAcessoNFe,
                        filial}, callback, asyncState);
        }
        
        /// <remarks/>
        public DownloadXMlNFe EndRealizarDownloadNFePorLoja(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DownloadXMlNFe)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RealizarDownloadNFePorCNPJ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DownloadXMlNFe RealizarDownloadNFePorCNPJ(string chaveAcessoNFe, string cnpjDestinatario) {
            object[] results = this.Invoke("RealizarDownloadNFePorCNPJ", new object[] {
                        chaveAcessoNFe,
                        cnpjDestinatario});
            return ((DownloadXMlNFe)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRealizarDownloadNFePorCNPJ(string chaveAcessoNFe, string cnpjDestinatario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RealizarDownloadNFePorCNPJ", new object[] {
                        chaveAcessoNFe,
                        cnpjDestinatario}, callback, asyncState);
        }
        
        /// <remarks/>
        public DownloadXMlNFe EndRealizarDownloadNFePorCNPJ(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DownloadXMlNFe)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VersaoEDL {
        
        private byte[] aplicativoField;
        
        private int tamanhoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Aplicativo {
            get {
                return this.aplicativoField;
            }
            set {
                this.aplicativoField = value;
            }
        }
        
        /// <remarks/>
        public int Tamanho {
            get {
                return this.tamanhoField;
            }
            set {
                this.tamanhoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadXMlNFe {
        
        private string chaveAcessoNFeField;
        
        private string cNPJDestinatarioField;
        
        private bool downloadOKField;
        
        private string msgRetornoField;
        
        /// <remarks/>
        public string ChaveAcessoNFe {
            get {
                return this.chaveAcessoNFeField;
            }
            set {
                this.chaveAcessoNFeField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJDestinatario {
            get {
                return this.cNPJDestinatarioField;
            }
            set {
                this.cNPJDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public bool DownloadOK {
            get {
                return this.downloadOKField;
            }
            set {
                this.downloadOKField = value;
            }
        }
        
        /// <remarks/>
        public string MsgRetorno {
            get {
                return this.msgRetornoField;
            }
            set {
                this.msgRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private int usuarioIdField;
        
        private string nomeField;
        
        private string dataHoraField;
        
        private string loginField;
        
        private bool alterarConfiguracaoField;
        
        private string erroField;
        
        private int filialField;
        
        /// <remarks/>
        public int UsuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string DataHora {
            get {
                return this.dataHoraField;
            }
            set {
                this.dataHoraField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public bool AlterarConfiguracao {
            get {
                return this.alterarConfiguracaoField;
            }
            set {
                this.alterarConfiguracaoField = value;
            }
        }
        
        /// <remarks/>
        public string Erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        public int Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NotaFiscalEntradaItem {
        
        private int idField;
        
        private System.Nullable<int> codigoProdutoField;
        
        private int digitoVerificadorField;
        
        private decimal quantidadeField;
        
        private decimal quantidadeBonificadaField;
        
        private string descricaoField;
        
        private System.Nullable<int> quantidadeEmbalagemExpedicaoField;
        
        private string permiteMultiplicadorField;
        
        private decimal valorUnitarioField;
        
        private System.Nullable<int> fornecedorField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CodigoProduto {
            get {
                return this.codigoProdutoField;
            }
            set {
                this.codigoProdutoField = value;
            }
        }
        
        /// <remarks/>
        public int DigitoVerificador {
            get {
                return this.digitoVerificadorField;
            }
            set {
                this.digitoVerificadorField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public decimal QuantidadeBonificada {
            get {
                return this.quantidadeBonificadaField;
            }
            set {
                this.quantidadeBonificadaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QuantidadeEmbalagemExpedicao {
            get {
                return this.quantidadeEmbalagemExpedicaoField;
            }
            set {
                this.quantidadeEmbalagemExpedicaoField = value;
            }
        }
        
        /// <remarks/>
        public string PermiteMultiplicador {
            get {
                return this.permiteMultiplicadorField;
            }
            set {
                this.permiteMultiplicadorField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Fornecedor {
            get {
                return this.fornecedorField;
            }
            set {
                this.fornecedorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NotaFiscalEntrada {
        
        private int idField;
        
        private string serieField;
        
        private string cnpjFornecedorField;
        
        private string cnpjCpfField;
        
        private NotaFiscalEntradaItem[] notaFiscalEntradaItemField;
        
        private ProdutoCodigoBarra[] codigosBarraField;
        
        private int fornecedorJuridicoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public string CnpjFornecedor {
            get {
                return this.cnpjFornecedorField;
            }
            set {
                this.cnpjFornecedorField = value;
            }
        }
        
        /// <remarks/>
        public string CnpjCpf {
            get {
                return this.cnpjCpfField;
            }
            set {
                this.cnpjCpfField = value;
            }
        }
        
        /// <remarks/>
        public NotaFiscalEntradaItem[] NotaFiscalEntradaItem {
            get {
                return this.notaFiscalEntradaItemField;
            }
            set {
                this.notaFiscalEntradaItemField = value;
            }
        }
        
        /// <remarks/>
        public ProdutoCodigoBarra[] CodigosBarra {
            get {
                return this.codigosBarraField;
            }
            set {
                this.codigosBarraField = value;
            }
        }
        
        /// <remarks/>
        public int FornecedorJuridico {
            get {
                return this.fornecedorJuridicoField;
            }
            set {
                this.fornecedorJuridicoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProdutoCodigoBarra {
        
        private string codigoBarrasField;
        
        private System.Nullable<int> codigoProdutoField;
        
        private bool internoField;
        
        private bool padraoField;
        
        /// <remarks/>
        public string CodigoBarras {
            get {
                return this.codigoBarrasField;
            }
            set {
                this.codigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CodigoProduto {
            get {
                return this.codigoProdutoField;
            }
            set {
                this.codigoProdutoField = value;
            }
        }
        
        /// <remarks/>
        public bool Interno {
            get {
                return this.internoField;
            }
            set {
                this.internoField = value;
            }
        }
        
        /// <remarks/>
        public bool Padrao {
            get {
                return this.padraoField;
            }
            set {
                this.padraoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Nfe {
        
        private System.Nullable<int> idField;
        
        private string chaveAcessoNfeField;
        
        private int numeroField;
        
        private string serieField;
        
        private int filialField;
        
        private string filialNomeField;
        
        private string situacaoField;
        
        private long cnpjEmissorField;
        
        private long cnpjDestinatarioField;
        
        private string erroField;
        
        private string[] divergenciasField;
        
        private NotaFiscalEntrada notaFiscalEntradaField;
        
        private System.DateTime dataEmissaoField;
        
        private string mensagemField;
        
        private bool temXMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ChaveAcessoNfe {
            get {
                return this.chaveAcessoNfeField;
            }
            set {
                this.chaveAcessoNfeField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public int Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
            }
        }
        
        /// <remarks/>
        public string FilialNome {
            get {
                return this.filialNomeField;
            }
            set {
                this.filialNomeField = value;
            }
        }
        
        /// <remarks/>
        public string Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
        
        /// <remarks/>
        public long CnpjEmissor {
            get {
                return this.cnpjEmissorField;
            }
            set {
                this.cnpjEmissorField = value;
            }
        }
        
        /// <remarks/>
        public long CnpjDestinatario {
            get {
                return this.cnpjDestinatarioField;
            }
            set {
                this.cnpjDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string Erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        public string[] Divergencias {
            get {
                return this.divergenciasField;
            }
            set {
                this.divergenciasField = value;
            }
        }
        
        /// <remarks/>
        public NotaFiscalEntrada NotaFiscalEntrada {
            get {
                return this.notaFiscalEntradaField;
            }
            set {
                this.notaFiscalEntradaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool TemXML {
            get {
                return this.temXMLField;
            }
            set {
                this.temXMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FornecedorJuridico {
        
        private int idField;
        
        private string cnpjField;
        
        private string razaoField;
        
        private string fantasiaField;
        
        private string erroField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        public string razao {
            get {
                return this.razaoField;
            }
            set {
                this.razaoField = value;
            }
        }
        
        /// <remarks/>
        public string fantasia {
            get {
                return this.fantasiaField;
            }
            set {
                this.fantasiaField = value;
            }
        }
        
        /// <remarks/>
        public string erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pedido {
        
        private PedidoItens[] pedidoItensField;
        
        private string erroField;
        
        /// <remarks/>
        public PedidoItens[] PedidoItens {
            get {
                return this.pedidoItensField;
            }
            set {
                this.pedidoItensField = value;
            }
        }
        
        /// <remarks/>
        public string erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PedidoItens {
        
        private int codigoProdutoField;
        
        private decimal quantidadeField;
        
        private decimal quantidadeAtendidaField;
        
        private string descricaoField;
        
        private string codigoBarrasField;
        
        private ProdutoCodigoBarra[] codigoBarraField;
        
        private int quantidadeEmbalagemExpedicaoField;
        
        private string permiteMultiplicadorField;
        
        private decimal valorUnitarioField;
        
        /// <remarks/>
        public int CodigoProduto {
            get {
                return this.codigoProdutoField;
            }
            set {
                this.codigoProdutoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public decimal QuantidadeAtendida {
            get {
                return this.quantidadeAtendidaField;
            }
            set {
                this.quantidadeAtendidaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoBarras {
            get {
                return this.codigoBarrasField;
            }
            set {
                this.codigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        public ProdutoCodigoBarra[] CodigoBarra {
            get {
                return this.codigoBarraField;
            }
            set {
                this.codigoBarraField = value;
            }
        }
        
        /// <remarks/>
        public int QuantidadeEmbalagemExpedicao {
            get {
                return this.quantidadeEmbalagemExpedicaoField;
            }
            set {
                this.quantidadeEmbalagemExpedicaoField = value;
            }
        }
        
        /// <remarks/>
        public string PermiteMultiplicador {
            get {
                return this.permiteMultiplicadorField;
            }
            set {
                this.permiteMultiplicadorField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolucaoItem {
        
        private string codigoBarrasField;
        
        private int codigoProdutoField;
        
        private decimal quantidadeField;
        
        private decimal qtdEstoqueField;
        
        private string descricaoField;
        
        private string erroField;
        
        private int idDevolucaoField;
        
        /// <remarks/>
        public string CodigoBarras {
            get {
                return this.codigoBarrasField;
            }
            set {
                this.codigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoProduto {
            get {
                return this.codigoProdutoField;
            }
            set {
                this.codigoProdutoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public decimal QtdEstoque {
            get {
                return this.qtdEstoqueField;
            }
            set {
                this.qtdEstoqueField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        public int IdDevolucao {
            get {
                return this.idDevolucaoField;
            }
            set {
                this.idDevolucaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Devolucao {
        
        private int idField;
        
        private int anoDiadoAnoField;
        
        private int sequencialAnoDiadoAnoField;
        
        private int idFornecedorJuridicoField;
        
        private string nomeFornecedorJuridicoField;
        
        private string cnpjFornecedorJuridicoField;
        
        private System.DateTime dataCadastroField;
        
        private string tipoPedidoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int AnoDiadoAno {
            get {
                return this.anoDiadoAnoField;
            }
            set {
                this.anoDiadoAnoField = value;
            }
        }
        
        /// <remarks/>
        public int SequencialAnoDiadoAno {
            get {
                return this.sequencialAnoDiadoAnoField;
            }
            set {
                this.sequencialAnoDiadoAnoField = value;
            }
        }
        
        /// <remarks/>
        public int IdFornecedorJuridico {
            get {
                return this.idFornecedorJuridicoField;
            }
            set {
                this.idFornecedorJuridicoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeFornecedorJuridico {
            get {
                return this.nomeFornecedorJuridicoField;
            }
            set {
                this.nomeFornecedorJuridicoField = value;
            }
        }
        
        /// <remarks/>
        public string CnpjFornecedorJuridico {
            get {
                return this.cnpjFornecedorJuridicoField;
            }
            set {
                this.cnpjFornecedorJuridicoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataCadastro {
            get {
                return this.dataCadastroField;
            }
            set {
                this.dataCadastroField = value;
            }
        }
        
        /// <remarks/>
        public string TipoPedido {
            get {
                return this.tipoPedidoField;
            }
            set {
                this.tipoPedidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NegociacaoProduto {
        
        private string codigoBarrasField;
        
        private System.Nullable<int> codigoProdutoField;
        
        private decimal quantidadeField;
        
        private string descricaoField;
        
        private decimal valorUnitarioField;
        
        private string erroField;
        
        /// <remarks/>
        public string CodigoBarras {
            get {
                return this.codigoBarrasField;
            }
            set {
                this.codigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CodigoProduto {
            get {
                return this.codigoProdutoField;
            }
            set {
                this.codigoProdutoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
            }
        }
        
        /// <remarks/>
        public string Erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NotaFiscalManual {
        
        private FornecedorNotaManual fornecedorNotaManualField;
        
        private NegociacaoProduto[] negociacaoProdutoField;
        
        /// <remarks/>
        public FornecedorNotaManual FornecedorNotaManual {
            get {
                return this.fornecedorNotaManualField;
            }
            set {
                this.fornecedorNotaManualField = value;
            }
        }
        
        /// <remarks/>
        public NegociacaoProduto[] NegociacaoProduto {
            get {
                return this.negociacaoProdutoField;
            }
            set {
                this.negociacaoProdutoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FornecedorNotaManual {
        
        private int fornecedorField;
        
        private string nomeField;
        
        private int fornecedorJuridicoField;
        
        private string cNPJFilialField;
        
        private int recebimentoField;
        
        private int validaPedidoField;
        
        private string cNPJFornecedorJuridicoField;
        
        private decimal valorTotalField;
        
        private decimal valorInformadoField;
        
        private System.DateTime dataEmissaoField;
        
        private int numeroField;
        
        private string serieField;
        
        private string erroField;
        
        private int filialField;
        
        private PedidoFornecedor[] pedidoFornecedorField;
        
        /// <remarks/>
        public int Fornecedor {
            get {
                return this.fornecedorField;
            }
            set {
                this.fornecedorField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public int FornecedorJuridico {
            get {
                return this.fornecedorJuridicoField;
            }
            set {
                this.fornecedorJuridicoField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJFilial {
            get {
                return this.cNPJFilialField;
            }
            set {
                this.cNPJFilialField = value;
            }
        }
        
        /// <remarks/>
        public int Recebimento {
            get {
                return this.recebimentoField;
            }
            set {
                this.recebimentoField = value;
            }
        }
        
        /// <remarks/>
        public int ValidaPedido {
            get {
                return this.validaPedidoField;
            }
            set {
                this.validaPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJFornecedorJuridico {
            get {
                return this.cNPJFornecedorJuridicoField;
            }
            set {
                this.cNPJFornecedorJuridicoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorInformado {
            get {
                return this.valorInformadoField;
            }
            set {
                this.valorInformadoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public string Erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        public int Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
            }
        }
        
        /// <remarks/>
        public PedidoFornecedor[] PedidoFornecedor {
            get {
                return this.pedidoFornecedorField;
            }
            set {
                this.pedidoFornecedorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PedidoFornecedor {
        
        private int fornecedorField;
        
        private string nomeField;
        
        private System.DateTime dataPedidoField;
        
        private int dataJulianaField;
        
        private int sequenciaJulianaField;
        
        private string situacaoField;
        
        private int filialField;
        
        /// <remarks/>
        public int Fornecedor {
            get {
                return this.fornecedorField;
            }
            set {
                this.fornecedorField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataPedido {
            get {
                return this.dataPedidoField;
            }
            set {
                this.dataPedidoField = value;
            }
        }
        
        /// <remarks/>
        public int DataJuliana {
            get {
                return this.dataJulianaField;
            }
            set {
                this.dataJulianaField = value;
            }
        }
        
        /// <remarks/>
        public int SequenciaJuliana {
            get {
                return this.sequenciaJulianaField;
            }
            set {
                this.sequenciaJulianaField = value;
            }
        }
        
        /// <remarks/>
        public string Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
        
        /// <remarks/>
        public int Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
            }
        }
    }
}
