//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.8762
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDL.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar seqüências de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Aberto {
            get {
                object obj = ResourceManager.GetObject("Aberto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barra {
            get {
                object obj = ResourceManager.GetObject("barra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barra2 {
            get {
                object obj = ResourceManager.GetObject("barra2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bateria_1 {
            get {
                object obj = ResourceManager.GetObject("bateria_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bateria_2 {
            get {
                object obj = ResourceManager.GetObject("bateria_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bateria_3 {
            get {
                object obj = ResourceManager.GetObject("bateria_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bateria_4 {
            get {
                object obj = ResourceManager.GetObject("bateria_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_cancel {
            get {
                object obj = ResourceManager.GetObject("button_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_ok {
            get {
                object obj = ResourceManager.GetObject("button_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Control_panel2 {
            get {
                object obj = ResourceManager.GetObject("Control_panel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap devolucao {
            get {
                object obj = ResourceManager.GetObject("devolucao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap drogariaaraujo {
            get {
                object obj = ResourceManager.GetObject("drogariaaraujo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap entrada {
            get {
                object obj = ResourceManager.GetObject("entrada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fundologin {
            get {
                object obj = ResourceManager.GetObject("fundologin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Key {
            get {
                object obj = ResourceManager.GetObject("Key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a É necessário bipar o crachá..
        /// </summary>
        internal static string MSGA001 {
            get {
                return ResourceManager.GetString("MSGA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Produto não foi identificado no documento e não pode ser recebido..
        /// </summary>
        internal static string MSGA002 {
            get {
                return ResourceManager.GetString("MSGA002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Quantidade informada é diferente da quantidade do documento..
        /// </summary>
        internal static string MSGA003 {
            get {
                return ResourceManager.GetString("MSGA003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Produto não identificado no pedido e não pode ser recebido..
        /// </summary>
        internal static string MSGA004 {
            get {
                return ResourceManager.GetString("MSGA004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Quantidade bipada ultrapassou a quantidade do pedido e o excedente não pode ser recebido..
        /// </summary>
        internal static string MSGA005 {
            get {
                return ResourceManager.GetString("MSGA005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Quantidade informada é maior que a quantidade do documento..
        /// </summary>
        internal static string MSGA006 {
            get {
                return ResourceManager.GetString("MSGA006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Produto # não tem a quantidade bipada em estoque para esta filial..
        /// </summary>
        internal static string MSGA008 {
            get {
                return ResourceManager.GetString("MSGA008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a O xml da NFe não foi enviado. Deseja realizar o download do xml dessa Nota?.
        /// </summary>
        internal static string MSGA009 {
            get {
                return ResourceManager.GetString("MSGA009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Existem produtos no documento que não foram bipados. .
        /// </summary>
        internal static string MSGC001 {
            get {
                return ResourceManager.GetString("MSGC001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Nota Fiscal não pode ser recebida nesta filial por pertencer à filial.
        /// </summary>
        internal static string MSGE002 {
            get {
                return ResourceManager.GetString("MSGE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Nota Fiscal bloqueada para recebimento..
        /// </summary>
        internal static string MSGE003 {
            get {
                return ResourceManager.GetString("MSGE003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Nota Fiscal não encontrada no Sistema. Não é possível realizar o recebimento..
        /// </summary>
        internal static string MSGE004 {
            get {
                return ResourceManager.GetString("MSGE004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Não é possível realizar o recebimento deste fornecedor sem NF-e..
        /// </summary>
        internal static string MSGE005 {
            get {
                return ResourceManager.GetString("MSGE005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Fornecedor não cadastrado no sistema. Não é possível realizar este recebimento..
        /// </summary>
        internal static string MSGE006 {
            get {
                return ResourceManager.GetString("MSGE006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Não existe pedido para este fornecedor. Recebimento não permitido..
        /// </summary>
        internal static string MSGE007 {
            get {
                return ResourceManager.GetString("MSGE007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Recebimento concluído com sucesso!.
        /// </summary>
        internal static string MSGI001 {
            get {
                return ResourceManager.GetString("MSGI001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Devolução concluída com sucesso!.
        /// </summary>
        internal static string MSGI002 {
            get {
                return ResourceManager.GetString("MSGI002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Download finalizado. Aguarde dois minutos para bipar a nota novamente..
        /// </summary>
        internal static string MSGI003 {
            get {
                return ResourceManager.GetString("MSGI003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Produto # não existe no mix da filial e não pode ser recebido..
        /// </summary>
        internal static string MSGI006 {
            get {
                return ResourceManager.GetString("MSGI006", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PorAbrir {
            get {
                object obj = ResourceManager.GetObject("PorAbrir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Não efetuou a leitura do crachá!.
        /// </summary>
        internal static string SYS001 {
            get {
                return ResourceManager.GetString("SYS001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a É obrigatório informar uma senha para acessar no sistema!.
        /// </summary>
        internal static string SYS002 {
            get {
                return ResourceManager.GetString("SYS002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Nota Fiscal já foi recebida..
        /// </summary>
        internal static string SYS003 {
            get {
                return ResourceManager.GetString("SYS003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Nota Fiscal é de devolução..
        /// </summary>
        internal static string SYS004 {
            get {
                return ResourceManager.GetString("SYS004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a É necessário informar todos os campos da chave de acesso..
        /// </summary>
        internal static string SYS005 {
            get {
                return ResourceManager.GetString("SYS005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Produto já foi bipado..
        /// </summary>
        internal static string SYS006 {
            get {
                return ResourceManager.GetString("SYS006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Não foi possível registrar os ítens da nota fiscal devido à queda de conexão com o servidor principal..
        /// </summary>
        internal static string SYS007 {
            get {
                return ResourceManager.GetString("SYS007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Não foi possível encontrar informações da filial..
        /// </summary>
        internal static string SYS008 {
            get {
                return ResourceManager.GetString("SYS008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a É necessário informar todos os dados da nota fiscal..
        /// </summary>
        internal static string SYS009 {
            get {
                return ResourceManager.GetString("SYS009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Já existem itens lançados. Se voltar, terá que recomeçar. Confirma?.
        /// </summary>
        internal static string SYS010 {
            get {
                return ResourceManager.GetString("SYS010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Valor total da nota está maior que o valor negociado..
        /// </summary>
        internal static string SYS011 {
            get {
                return ResourceManager.GetString("SYS011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Para acessar as Configurações, é necessário bipar o crachá e informar a senha..
        /// </summary>
        internal static string SYS012 {
            get {
                return ResourceManager.GetString("SYS012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Não tem permissão para acessar a janela de Configurações..
        /// </summary>
        internal static string SYS013 {
            get {
                return ResourceManager.GetString("SYS013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Produto # não tem quantidade em estoque para esta filial..
        /// </summary>
        internal static string SYS014 {
            get {
                return ResourceManager.GetString("SYS014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Não foi possível registrar os ítens da devolução devido à queda de conexão com o servidor principal..
        /// </summary>
        internal static string SYS015 {
            get {
                return ResourceManager.GetString("SYS015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Não existem ítens bipados..
        /// </summary>
        internal static string SYS016 {
            get {
                return ResourceManager.GetString("SYS016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a O pedido bipado não está na relação..
        /// </summary>
        internal static string SYS017 {
            get {
                return ResourceManager.GetString("SYS017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a É necessário informar todos os dados do romaneio..
        /// </summary>
        internal static string SYS018 {
            get {
                return ResourceManager.GetString("SYS018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Nota recusada por divergência no recebimento..
        /// </summary>
        internal static string SYS019 {
            get {
                return ResourceManager.GetString("SYS019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Nota recusada por inconsistência..
        /// </summary>
        internal static string SYS020 {
            get {
                return ResourceManager.GetString("SYS020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Recebimento da nota cancelado pelo operador..
        /// </summary>
        internal static string SYS021 {
            get {
                return ResourceManager.GetString("SYS021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a O código bipado não corresponde ao código do fornecedor..
        /// </summary>
        internal static string SYS022 {
            get {
                return ResourceManager.GetString("SYS022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Nota Fiscal está no sistema, mas ainda não foi liberada para recebimento..
        /// </summary>
        internal static string SYS023 {
            get {
                return ResourceManager.GetString("SYS023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Existe uma nova versão do aplicativo atualizador do EDL, deseja acessar as configurações para iniciar a atualização?.
        /// </summary>
        internal static string SYS024 {
            get {
                return ResourceManager.GetString("SYS024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Não foi possível conectar com servidor, verifique rede ou endereço de conexão..
        /// </summary>
        internal static string SYS998 {
            get {
                return ResourceManager.GetString("SYS998", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Ocorreu quebra de conexão ou inconsistência de dados, não foi possível concluir o processamento: .
        /// </summary>
        internal static string SYS999 {
            get {
                return ResourceManager.GetString("SYS999", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap verde {
            get {
                object obj = ResourceManager.GetObject("verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vermelho {
            get {
                object obj = ResourceManager.GetObject("vermelho", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
